spring:
  application:
    name: reservalab

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/reserva_lab
    driverClassName: org.postgresql.Driver
    username: reservalab
    password: reservalab

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: meuSegredoMuitoForteComMaisDe32Caracteres123
  expiration-ms: 86400000